name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: '.'
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Restore NuGet
        run: nuget restore "Malis Mission Roller 2.sln"
      - name: Build
        run: msbuild "Malis Mission Roller 2.sln" /p:Configuration=Release
      - name: Write version file
        run: echo ${{ github.ref_name }} > "bin/Release/MissionRoller.version"
      - name: Package release DLL
        run: |
          mkdir -p Release
          Compress-Archive -Path "bin/Release/Malis Mission Roller 2.dll" -DestinationPath "Release/MissionRoller-${{ github.ref_name }}.zip"
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: Release/MissionRoller-${{ github.ref_name }}.zip